logging:
  level:
    com.cdkj: debug
  config: classpath:config/logback-spring.xml

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.244:3306/bootdo?useUnicode=true&characterEncoding=utf8
    username: sms
    password: sms
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
#    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
#    driverClassName: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@192.168.1.244:7021:orcl
#    username: dist_dev
#    password: dist_dev
    # 合并多个DruidDataSource的监控数据
    #useGlobalDataSourceStat: true
  #REDIS SETTING
  redis:
    cluster:
      #REDIS 集群信息节点配置
      nodes: 192.168.1.244:7000,192.168.1.244:7001,192.168.1.244:7002,192.168.1.244:7003,192.168.1.244:7004,192.168.1.244:7005
      #失败之后的重试次数
      max-redirects: 12
    #默认使用db0进行存储
    database: 0
    #连接池信息
    pool:
      #最大连接数
      max-active: 100
      max-idle: 10
      min-idle: 1
